# Generated by Django 3.1.2 on 2020-10-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201020_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.groups'),
            preserve_default=False,
        ),
    ]
