# Generated by Django 3.1.2 on 2020-10-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_posts_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
