# Generated by Django 3.1.2 on 2020-10-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201021_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='initiated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.posts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
