# Generated by Django 3.1.2 on 2020-10-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201023_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('experience', 'experience'), ('comment', 'comment'), ('question', 'question')], default='', max_length=100),
        ),
    ]
