# Generated by Django 3.1.2 on 2020-10-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_comments_is_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification_certificate',
            field=models.ImageField(default='', upload_to='doctor/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.specialization'),
            preserve_default=False,
        ),
    ]
