# Generated by Django 3.1.2 on 2020-10-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201024_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification_certificate',
            field=models.FileField(upload_to='doctor/'),
        ),
    ]
