# Generated by Django 3.1.2 on 2020-10-24 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='listing_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='services',
            field=models.CharField(choices=[('medical', 'medical'), ('hospital', 'hospital'), ('clinic', 'clinic')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
